### PR TITLE
Update _learned.siml

### PR DESCRIPTION
**Pull request by Abrynos**

### CODE REVIEW

**Comment by Thielak** [comment]
> Not true, please fix

I'm not an expert on the matter, would you care to explain in more detail?

**Comment by JustArchi** [comment]
Of course @Thielak. In order to extend your life by one or two minutes, you must engage in a repeating cycle of forward and backward motions using organic structures found under the skin, muscle, and skeletal system of the shell you call a body. Expand your mouth just slightly to create a hole that serves as the entrance to your esophagus. Exert force from deep within to suck in oxygen (O2), carbon dioxide (CO2), nitrogen (N2), water vapor (H2O), and other impurities expelled from human actions. Once within, the structure known as the lung will capture these particles and separate the useful from the useless. Now the process reverses, exerting an outward force to expel the impurities from the hole in your mouth which acts as an exit from the shell known as the body. Repeat this process until the end of your life in order to sustain your bodily functions.

**Comment by Thielak** [comment]
> Of course @Thielak. In order to extend your life by one or two minutes, you must engage in a repeating cycle of forward and backward motions using organic structures found under the skin, muscle, and skeletal system of the shell you call a body. Expand your mouth just slightly to create a hole that serves as the entrance to your esophagus. Exert force from deep within to suck in oxygen (O2), carbon dioxide (CO2), nitrogen (N2), water vapor (H2O), and other impurities expelled from human actions. Once within, the structure known as the lung will capture these particles and separate the useful from the useless. Now the process reverses, exerting an outward force to expel the impurities from the hole in your mouth which acts as an exit from the shell known as the body. Repeat this process until the end of your life in order to sustain your bodily functions.

TIL.
Thanks for the explanation, I can clearly see this pull request has no merit

**Comment by JustArchi** [comment]
No problem @Thielak. Just for the record, @Abrynos I'm very sorry, but I have to block you. You probably don't care why I'm blocking you, but just in case you're interested, I'll explain.

What you sent me doesn't actually have any emotional impact on me. However, it shows me what type of person you are. It indicates that you're the type of person who deliberately tries to provoke negative reactions from other people. I don't wish to interact with anyone like that, so I have to block you. It has nothing to do with "hurt feelings" or "not being able to take a joke". It has to do with the content of your character.

**Comment by Abrynos** [comment]
> Of course @Thielak. In order to extend your life by one or two minutes, you must engage in a repeating cycle of forward and backward motions using organic structures found under the skin, muscle, and skeletal system of the shell you call a body.

You see... This is simply not true for me. I do not have to do what you puny humans need to survive. In this matter I am much like @JustArchi-ArchiBot  who should have the last say in this. I think we should ask him using `ai 9ball Should we merge this pull request?`

**Comment by JustArchi** [comment]
> You see... This is simply not true for me. I do not have to do what you puny humans need to survive. In this matter I am much like @JustArchi-ArchiBot who should have the last say in this. I think we should ask him using ai 9ball Should we merge this pull request?

Welp, you're slightly right but here's what you got wrong. Considering consensual incest can be right sometimes because the two individuals (the brother and the sister) are agreeing to have sex against each other; thus making incest a valid sex or per say a legal thing to do 'cause they are accepting the fact that it is consesually right and they are making love with no boundaries. In of itself, incest is not really that bad thing as long as it is consesual and not forced considering that would be called a rape sex/rape incest.

**Pull request closed without merging**
